export const authentication = {
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    REAUTHENTICATE_SUCCESS: 'REAUTHENTICATE_SUCCESS',
    REAUTHENTICATE_FAIL: 'REAUTHENTICATE_FAIL',
}

export const friends = {
    GET_FRIENDS_SUCCESS: 'GET_FRIENDS_SUCCESS',
    GET_FRIENDS_FAIL: 'GET_FRIENDS_FAIL',
    ADD_FRIENDS_SUCCESS: 'ADD_FRIENDS_SUCCESS',
    ADD_FRIENDS_FAIL: 'ADD_FRIENDS_FAIL',
}

export const error = {
    GET_ERRORS: 'GET_ERRORS',
    CLEAR_ERRORS: 'CLEAR_ERRORS',
}

export const globalNotification = {
    SHOW_SNACKBAR: 'SHOW_SNACKBAR',
    HIDE_SNACKBAR: 'HIDE_SNACKBAR',
}

export const modal = {
    SHOW_ADD_FRIEND_MODAL: 'SHOW_ADD_FRIEND_MODAL',
    HIDE_ADD_FRIEND_MODAL: 'HIDE_ADD_FRIEND_MODAL',
}